---
title: "Honors Class05 Activity: Practice Quiz Questions"
jupyter: datascience
format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
    include-in-header: 
        text:
            \usepackage{wrapfig}
---
## Team Members: _____________________________________
## _______________________________________________

## Learning Objectives
* Test your understanding
* Prepare for Quiz 1

This activity is practice for the first quiz. Answer the questions based on your programming experience.  If you are stuck, talk with a team member. If you are *really* stuck, then try the code in a Jupyter notebook, but keep in mind that you won't be able to do this on the quiz.

#### Problem 1: What is the output?
```{python}
# | output: false
a = "I'm not arguing."
b = "I'm just explaining why I'm right."
print(a + b)
```
\vspace {1 cm}

#### Problem 2: What is the output?
```{python}
# | output: false
winter_months = ["December", "January", "February", "March"]
print(winter_months[3])
```
\vspace {1 cm}

#### Problem 3: What is the output?
```{python}
# | output: false
x = 2**3 / 8 + 3
print(x)
```
\vspace {1 cm}

#### Problem 4: What is the output?
```{python}
#| eval: false
# What do you call a fish with no eyes?
answer = "fish".replace("i","")
answer
```
\vspace {1 cm}


#### Problem 5: Explain the error.
```{python}
#| eval: false
my_tuple = ("Dr. Nyquist", "Geophysicist", "CST")
my_tuple[2] = "Earth & Environmental Science"
```
TypeError: 'tuple' object does not support item assignment
\vspace {1 cm}

#### Problem 6: What is the output?
```{python}
#| eval: false
import numpy as np
a = 3
b = 4
c = np.sqrt(a**2 + b**2)
```
\vspace {1 cm}

#### Problem 7: What is the output?
```{python}
#| eval: false
np.arange (1, 7)
```
\vspace {1 cm}

#### Problem 8: What is the output?
```{python}
#| eval: false
len(“Data Science”)
```
\vspace {1 cm}

#### Problem 9: What is the output?
```{python}
# | eval: false
from datascience import *

x = make_array(1, -3, 12, -7, 0, -50)
max(abs(x))
```
\vspace {1 cm}

#### Problem 10: What is the output?
```{python}
#| eval: false
colors = ["red", "blue", "green"]
colors.append("yellow")
print(colors)
```
\newpage

#### The next 10 questions are based on the following data table named `dice_results`.
```{python}
# | echo: false
from datascience import *

# Arrays
team = ["Team A", "Team B", "Team C", "Team D", "Team E", "Team F", "Team G", "Team H"]

rolls = [50, 50, 50, 50, 50, 50, 50, 50]
avg_sum = [6.4, 7.1, 6.8, 7.3, 6.6, 7.0, 7.5, 6.9]
num_sevens = [7, 9, 8, 11, 6, 8, 12, 9]
deviation = [avg - 7 for avg in avg_sum]

# Create the table
dice_results = Table().with_columns(
    "Team",
    team,
    "Rolls",
    rolls,
    "Average Sum",
    avg_sum,
    "Number of 7s",
    num_sevens,
    "Avg − 7",
    deviation,
)
dice_results
```

#### Problem 11: What is the output?
```{python}
#| eval: false
import numpy as np

np.max(dice_results.column("Number of 7s"))
```
\vspace {1 cm}

#### Problem 12: What is the output?
```{python}
#| eval: false
dice_results.take(2)
```
\vspace {1 cm}

#### Problem 13: What is the output?
```{python}
# | eval: false
dice_results.where("Average Sum", are.below(6.5))
```

#### Problem 13: What is the output?
```{python}
# | eval: false
dice_results.where("Average Sum", are.below(6.5))
```
\vspace {1 cm}

#### Problem 14: 
Write python code to find the average number of 7s.
\vspace {1 cm}

#### Problem 15: 
Write python code to sort the table by Avg - 7.
\newpage

## Design Your Own Quiz Questions
Work with your team to design up to five quiz questions. If you design good ones, you may see them on the actual quiz!