---
title: "Honors Class06 Activity: Practice with Tables -- Breakfast Cereals"
jupyter: datascience
format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
    include-in-header: 
        text:
            \usepackage{wrapfig}
---
\vspace{-2.0 cm}

## Team Members: _____________________________________
## _______________________________________________

## Learning Objectives
* Read data into tables
* Understanding metadata
* Manipulating data tables

You will be using data tables for just about everything the rest of the semester, so let warm-up today with exercise designed to review many of the basic table operations. And what could be better on a table than some breakfast cereal? We'll start by loading a data with the following information:

Content
Fields in the dataset:

Name: Name of cereal

```
- mfr: Manufacturer of cereal
- A = American Home Food Products;
- G = General Mills
- K = Kelloggs
- N = Nabisco
- P = Post
- Q = Quaker Oats
- R = Ralston Purina
- type:
- cold
- hot
- calories: calories per serving
- protein: grams of protein
- fat: grams of fat
- sodium: milligrams of sodium
- fiber: grams of dietary fiber
- carbo: grams of complex carbohydrates
- sugars: grams of sugars
- potass: milligrams of potassium
- vitamins: vitamins and minerals - 0, 25, or 100, indicating the typical percentage of FDA recommended
- shelf: display shelf (1, 2, or 3, counting from the floor)
- weight: weight in ounces of one serving
- cups: number of cups in one serving
- rating: a rating of the cereals (Possibly from Consumer Reports?)
```

**Data the describes the data is called "metadata." Metadata is a critical component of every data set.**

Acknowledgements
These datasets have been gathered and cleaned up by Petra Isenberg, Pierre Dragicevic and Yvonne Jansen. The data was downloaded from Kaggle.

#### Problem 1: What is the output?
```{python}
# | output: false
a = "I'm not arguing."
b = "I'm just explaining why I'm right."
print(a + b)
```
\vspace {1 cm}

